spring:
  application:
    name: ecom-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payments/**
              filters:
                - name: Retry
                  args:
                    retries: 3
                    methods: GET
                    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                    exceptions:
                      - java.io.IOException
                      - java.util.concurrent.TimeoutException
                    backoff:
                      firstBackoff: 100ms
                      maxBackoff: 500ms
                      factor: 2
                      basedOnPreviousValue: false
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/inventory/**
              filters:
                - name: Retry
                  args:
                    retries: 3
                    methods: GET
                    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
                    exceptions:
                      - java.io.IOException
                      - java.util.concurrent.TimeoutException
                      - java.lang.RuntimeException
                    backoff:
                      firstBackoff: 100ms
                      maxBackoff: 500ms
                      factor: 2
                      basedOnPreviousValue: false


server:
  port: 9090

gateway:
  rate-limit:
    limit-for-period: 100
    limit-refresh-period: 1s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
